//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATACAO_AUDITORIA
    {
        public long id { get; set; }
        public string dado_original { get; set; }
        public string dado_alterado { get; set; }
        public string tipo { get; set; }
        public string tabela { get; set; }
        public System.DateTime data { get; set; }
        public string usuario { get; set; }
    }
}
