//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATACAO_ARQUIVO
    {
        public long id { get; set; }
        public string nome { get; set; }
        public string extensao { get; set; }
        public string tipo { get; set; }
        public long tamanho { get; set; }
        public byte[] binario { get; set; }
    }
}
