//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATACAO_USUARIO
    {
        public long id { get; set; }
        public long colaborador_id { get; set; }
        public string usuario_conta { get; set; }
        public long status_id_conta { get; set; }
        public System.DateTime data_ativacao_conta { get; set; }
        public Nullable<System.DateTime> data_desativacao_conta { get; set; }
        public string usuario_active_directory { get; set; }
        public long status_id_active_directory { get; set; }
        public string usuario_exchange { get; set; }
        public long status_id_exchange { get; set; }
        public string usuario_sei { get; set; }
        public long status_id_sei { get; set; }
        public Nullable<long> usuario_send { get; set; }
        public long status_id_send { get; set; }
        public string motivo_observacoes { get; set; }
    }
}
