//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATACAO_SUBSTITUTO
    {
        public long id { get; set; }
        public long usuario_id_titular { get; set; }
        public long usuario_id_suplente { get; set; }
        public System.DateTime data_inicio_substituicao { get; set; }
        public System.DateTime data_fim_substituicao { get; set; }
        public string motivo_observacoes { get; set; }
        public long status { get; set; }
    }
}
