//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATACAO_COLABORADOR
    {
        public long id { get; set; }
        public int codigo_pessoa { get; set; }
        public string chapa { get; set; }
        public Nullable<int> matricula { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string email_corporativo { get; set; }
        public string email_pessoal1 { get; set; }
        public string email_pessoal2 { get; set; }
        public string codigo_recebimento { get; set; }
        public string codigo_situacao { get; set; }
        public string situacao { get; set; }
        public string codigo_tipo { get; set; }
        public string centro_de_custo { get; set; }
        public string codigo_unidade_sei { get; set; }
        public Nullable<short> codigo_unidade { get; set; }
        public string unidade { get; set; }
        public string codigo_secao { get; set; }
        public string secao { get; set; }
        public string codigo_cargo { get; set; }
        public string cargo { get; set; }
        public string codigo_funcao { get; set; }
        public string funcao { get; set; }
        public Nullable<System.DateTime> data_admissao { get; set; }
        public string tipo_admissao { get; set; }
        public Nullable<System.DateTime> data_demissao { get; set; }
        public string tipo_demissao { get; set; }
        public Nullable<System.DateTime> data_inicio_ferias { get; set; }
        public Nullable<System.DateTime> data_fim_ferias { get; set; }
        public Nullable<System.DateTime> data_inicio_afastamento { get; set; }
        public Nullable<System.DateTime> data_fim_afastamento { get; set; }
        public string gestor_chapa { get; set; }
        public string gestor_nome { get; set; }
        public string gestor_email { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string criado_por { get; set; }
        public Nullable<System.DateTime> criado_em { get; set; }
        public string modificado_por { get; set; }
        public Nullable<System.DateTime> modificado_em { get; set; }
    }
}
