//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSOS
    {
        public int id { get; set; }
        public int idCurso { get; set; }
        public string curso { get; set; }
        public int idUnidade { get; set; }
    }
}
