//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPOSITO
    {
        public DEPOSITO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int id { get; set; }
        public string deposito { get; set; }
        public int idUnidade { get; set; }
        public bool status { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
