//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA_INSTRUTOR
    {
        public int id { get; set; }
        public int idDisciplina { get; set; }
        public long idInstrutor { get; set; }
        public int idTurma { get; set; }
    }
}
