//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCIPLINA
    {
        public int id { get; set; }
        public int idDisciplina { get; set; }
        public string disciplina { get; set; }
        public System.DateTime dataInicial { get; set; }
        public System.DateTime dataFinal { get; set; }
        public string horaInicial { get; set; }
        public string horaFinal { get; set; }
        public int cargaHoraria { get; set; }
        public string supervisor { get; set; }
        public string cpfSupervisor { get; set; }
        public string freqSemanal { get; set; }
        public int idTurma { get; set; }
    }
}
