//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estoqueEntities : DbContext
    {
        public estoqueEntities()
            : base("name=estoqueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<ENTRADA> ENTRADA { get; set; }
        public DbSet<DEPOSITO> DEPOSITO { get; set; }
        public DbSet<CURSOS> CURSOS { get; set; }
        public DbSet<UNIDADE> UNIDADE { get; set; }
        public DbSet<TURMA> TURMA { get; set; }
        public DbSet<DISCIPLINA> DISCIPLINA { get; set; }
        public DbSet<DISCIPLINA_INSTRUTOR> DISCIPLINA_INSTRUTOR { get; set; }
        public DbSet<INSTRUTOR> INSTRUTOR { get; set; }
        public DbSet<PLANEJAMENTO> PLANEJAMENTO { get; set; }
        public DbSet<LISTA_BASICA> LISTA_BASICA { get; set; }
        public DbSet<ENTRADA_AUXILIAR> ENTRADA_AUXILIAR { get; set; }
        public DbSet<ITENS_ENTRADA> ITENS_ENTRADA { get; set; }
        public DbSet<PRODUTO> PRODUTO { get; set; }
        public DbSet<SAIDA_AUXILIAR> SAIDA_AUXILIAR { get; set; }
        public DbSet<PLANEJAMENTO_AUXILIAR> PLANEJAMENTO_AUXILIAR { get; set; }
        public DbSet<SAIDA> SAIDA { get; set; }
        public DbSet<PLANEJAMENTO_ITENS_EXTRA> PLANEJAMENTO_ITENS_EXTRA { get; set; }
    }
}
