//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_AFASTADO
    {
        public long id { get; set; }
        public string chapa { get; set; }
        public Nullable<long> matricula { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public string active_directory_path { get; set; }
        public Nullable<System.DateTime> ultima_movimentacao { get; set; }
        public string usuario_logado { get; set; }
        public Nullable<long> situacao { get; set; }
        public string status_active_directory { get; set; }
        public string status_exchange { get; set; }
        public string status_sei { get; set; }
        public string status_send { get; set; }
    }
}
