//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_DIRETORIO
    {
        public long id { get; set; }
        public string secao_codigo { get; set; }
        public string secao_nome { get; set; }
        public string centro_de_custo { get; set; }
        public string diretorio_nome { get; set; }
        public string diretorio { get; set; }
    }
}
