//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GC_USUARIOS
    {
        public long id { get; set; }
        public string chapa { get; set; }
        public Nullable<long> matricula { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string email_pessoal { get; set; }
        public string email_corporativo { get; set; }
        public string situacao { get; set; }
        public string tipo { get; set; }
        public string centro_de_custo { get; set; }
        public string unidade_codigo { get; set; }
        public string unidade { get; set; }
        public string secao_codigo { get; set; }
        public string secao { get; set; }
        public string funcao_codigo { get; set; }
        public string funcao { get; set; }
        public Nullable<System.DateTime> data_admissao { get; set; }
        public Nullable<System.DateTime> data_demissao { get; set; }
        public string gestor_chapa { get; set; }
        public string gestor_nome { get; set; }
        public string gestor_email { get; set; }
        public string telefone1 { get; set; }
        public string telefone2 { get; set; }
        public string telefone3 { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string rua { get; set; }
        public Nullable<long> numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string usuario { get; set; }
        public string ad_usuario { get; set; }
        public string exchange_usuario { get; set; }
        public string sei_usu_id { get; set; }
        public Nullable<long> send_cod_usuario { get; set; }
    }
}
