//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUTOR
    {
        public long id { get; set; }
        public long idInstrutor { get; set; }
        public string instrutor { get; set; }
        public string cpf { get; set; }
        public Nullable<int> idUnidade { get; set; }
    }
}
