//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_BASICA
    {
        public LISTA_BASICA()
        {
            this.PLANEJAMENTO = new HashSet<PLANEJAMENTO>();
        }
    
        public int id { get; set; }
        public int idGrade { get; set; }
        public int idCurso { get; set; }
        public int codSei { get; set; }
        public string unidMedida { get; set; }
        public Nullable<int> quantEstimada { get; set; }
        public string observacao { get; set; }
    
        public virtual ICollection<PLANEJAMENTO> PLANEJAMENTO { get; set; }
    }
}
