//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANEJAMENTO_AUXILIAR
    {
        public int id { get; set; }
        public int idPlanejamento { get; set; }
        public int codSei { get; set; }
        public long idInstrutor { get; set; }
        public int quantidade { get; set; }
        public string justificativa { get; set; }
        public int idTurma { get; set; }
        public string aula { get; set; }
        public int idCurso { get; set; }
        public int idUnidade { get; set; }
    }
}
