//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public PRODUTO()
        {
            this.ITENS_ENTRADA = new HashSet<ITENS_ENTRADA>();
        }
    
        public int id { get; set; }
        public string codBarra { get; set; }
        public int codSei { get; set; }
        public string produto { get; set; }
        public string unidMedida { get; set; }
        public Nullable<decimal> valorUnitario { get; set; }
    
        public virtual ICollection<ITENS_ENTRADA> ITENS_ENTRADA { get; set; }
    }
}
