//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAIDA
    {
        public int id { get; set; }
        public System.DateTime dataSaida { get; set; }
        public decimal despesaRealizada { get; set; }
        public int quantidadeRetorno { get; set; }
        public decimal valorRetorno { get; set; }
        public string aula { get; set; }
        public int idCurso { get; set; }
        public int idUnidade { get; set; }
        public int idTurma { get; set; }
        public int idUsuario { get; set; }
        public int codSei { get; set; }
        public bool status { get; set; }
    }
}
