//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleEstoque.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURMA
    {
        public int id { get; set; }
        public int idTurma { get; set; }
        public int idCurso { get; set; }
        public string codTurma { get; set; }
        public string codOrcamentario { get; set; }
        public string turma { get; set; }
        public string situacao { get; set; }
        public System.DateTime dataInicial { get; set; }
        public System.DateTime dataFinal { get; set; }
        public string horaInicial { get; set; }
        public string horaFinal { get; set; }
        public string turno { get; set; }
        public int cargaHoraria { get; set; }
        public int vagas { get; set; }
        public int numAlunos { get; set; }
        public int idUnidade { get; set; }
    }
}
